name: Tests
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
    steps:
    # Set up Flutter.
    - name: Clone Flutter repository with master channel
      uses: subosito/flutter-action@v2.19.0
      with:
        channel: master
    - run: flutter doctor -v

    # Checkout gallery code and get packages.
    - name: Checkout gallery code
      uses: actions/checkout@v4
    - run: flutter pub get

    # Analyze, check formatting, and run unit tests.
    - run: flutter analyze
    - name: Ensure the Dart code is formatted correctly
      run: dart format -o none --set-exit-if-changed .
    - name: Run Flutter unit tests
      run: flutter test
    - name: Build Web
      run: flutter build web
    - name: Publish to Github Pages
      if: ${{ matrix.os == 'ubuntu-22.04' && github.event_name == 'push' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
